[project]
name = "capstone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cvzone>=1.6.1",
    "opencv-python>=4.11.0.86",
]
